---
openshift_cluster_content:
- object: app-builds
  content:
  - name: angular-sample-build
    template: "https://raw.githubusercontent.com/rht-labs/labs-ci-cd/v3.10.0/openshift-templates/s2i-app-build/template-with-secrets.yml"
    params: "{{ playbook_dir }}/params/build"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - build
- object: dev-stage
  content:
  - name: angular-sample-dev-deploy
    template: "{{ playbook_dir }}/openshift-templates/angular-sample-deploy.yml"
    params: "{{ playbook_dir }}/params/dev"
    namespace: "{{ dev_namespace }}"
    tags:
    - dev
    - dev-deploy
- object: demo-stage
  content:
  - name: angular-sample-demo-deploy
    template: "{{ playbook_dir }}/openshift-templates/angular-sample-deploy.yml"
    params: "{{ playbook_dir }}/params/demo"
    namespace: "{{ demo_namespace }}"
    tags:
    - demo
    - demo-deploy
